names:
- resistor
- capacitor_polarized
- capacitor_unpolarized
- inductor
- diode
- led
- transistor_npn
- transistor_pnp
- ic_dip
- op_amp
- microcontroller
- and_gate
- or_gate
- not_gate
- nand_gate
- nor_gate
- xor_gate
- voltage_source
- current_source
- ground
- vcc
- wire
- junction
- terminal
- multimeter
- oscilloscope
- function_generator
nc: 27
path: D:\dev_packages\demo-sim\backend\circuit_dataset
test: images/test
train: images/train
val: images/val
